// Metadata
import type { Metadata } from "next";
// Styles
import "./globals.css";
// Fonts
import { Inter, Cairo  } from "next/font/google";
// Providers
import ClientThemeProvider from "@/app/themes/ClientThemeProvider";
import ClientLanguageProvider from "@/app/lang/ClientLanguageProvider";
// import Components
import Header from "@/app/components/layout/Header";
import Footer from "@/app/components/layout/Footer";

// Fonts
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});
const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["400", "500", "700"],
  variable: "--font-cairo",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  const direction = params.lang === "ar" ? "rtl" : "ltr";

  return (
    <html lang={params.lang} dir={direction}>
      <body className={`${inter.variable} ${cairo.variable}`}>
        <ClientThemeProvider>
          <ClientLanguageProvider defaultLanguage={params.lang as "en" | "ar"}>
            <Header />
            {children}
            <Footer />
          </ClientLanguageProvider>
        </ClientThemeProvider>
      </body>
    </html>
  );
}
